### ISSUE TITLE
WeChat Group QrCode Expired

### ISSUE THREAD

**Issue by auula** [ASTTeam/CodeQL#3]
您好，readme 上的二维码已经过期了，麻烦你更新一下，或者你给我微信号我添加你，拉我进群谢谢。

**Comment by 0e0w** [comment]
https://i.postimg.cc/MKh8n1LK/20221010083807.png

**Comment by auula** [comment]
> https://i.postimg.cc/MKh8n1LK/20221010083807.png

thank.
